version: "3"
services:
  
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  funmoney:
    depends_on:
      - funmoney-frontend
    container_name: funmoney
    restart: unless-stopped
    ports:
      - 8082:8080
    image: funmoney
    environment:
      - CURRENCY=${CURRENCY}
      - CAP=${CAP}

  funmoney-frontend:
    restart: unless-stopped
    depends_on:
      - mongo
    container_name: funmoney-frontend
    ports:
      - 8002:8080
    image: funmoney-frontend
    environment:
      - ENV=${ENV}
